# Generated by Django 3.0.4 on 2020-03-31 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='teal', max_length=100, verbose_name='cor'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_created', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('sources', models.ManyToManyField(related_name='tags', related_query_name='tag', to='portal.Source')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tag_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
