# Generated by Django 3.0.4 on 2020-04-02 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_source_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='color',
        ),
    ]
