# Generated by Django 3.0.4 on 2020-04-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_remove_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='app_store',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='App Store'),
        ),
        migrations.AddField(
            model_name='source',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='source',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Instgram'),
        ),
        migrations.AddField(
            model_name='source',
            name='play_store',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Play Store'),
        ),
        migrations.AddField(
            model_name='source',
            name='twitter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Twitter'),
        ),
        migrations.AddField(
            model_name='source',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='source',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='URL'),
        ),
    ]
