# Generated by Django 3.0.4 on 2020-04-05 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_auto_20200403_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='url',
        ),
        migrations.AddField(
            model_name='source',
            name='site',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site'),
        ),
        migrations.AlterField(
            model_name='source',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads', verbose_name='imagem'),
        ),
    ]
